### ISSUE TITLE
Hi, I have seen the article and the coder. I don't know how the concated images in the train/test dir been created?  How to get the keypoint images?

### ISSUE THREAD

**Issue by wutan-lab** [Ha0Tang/C2GAN#1]

**Comment by Ha0Tang** [comment]
Have you tried `bash ./datasets/download_c2gan_dataset.sh RaFD_image_landmark`? Let me know if you have any further questions.

**Comment by wutan-lab** [comment]
> Have you tried `bash ./datasets/download_c2gan_dataset.sh RaFD_image_landmark`? Let me know if you have any further questions.

Sorry, I didn't notice that the code has been updated. I downloaded it several weeks ago. Thanks for your remind.

**Comment by Ha0Tang** [comment]
No worries.
