### ISSUE TITLE
Er, I downloaded the Radboud Faces Database, but how can I get images like in the RaFD_landmark_figure folder?

### ISSUE THREAD

**Issue by wutan-lab** [Ha0Tang/C2GAN#2]

**Comment by Ha0Tang** [comment]
What images in the RaFD_landmark_figure folder? I don't quite understand your question.

**Comment by wutan-lab** [comment]
> What images in the RaFD_landmark_figure folder? I don't quite understand your question.

I'm sorry I didn't make it clear. Now I want to make a similar database, but I don't know how to use the keypoint information to get the corresponding landmark figure, which may be called "starmap" with only black dots on the white background. Just like the Radboud dataset requires four pictures to be connected, and I am missing the two "starmaps".

**Comment by Ha0Tang** [comment]
I think the corresponding landmark figure also included in the `RaFD_landmark_figure`. Let me know this is what you want.

**Comment by wutan-lab** [comment]
> 
> 
> I think the corresponding landmark figure also included in the `RaFD_landmark_figure`. Let me know this is what you want.

What I need is the method of how to generate the starmaps, not the images. Maybe I should look for more information about the dataset. Anyway, thanks a lot for your patient response.

**Comment by Ha0Tang** [comment]
Hi, the code `./scripts/convert_pts_to_figure.m` is uploaded now. Let me know if this is ok with you.

**Comment by wutan-lab** [comment]
> 
> 
> Hi, the code `./scripts/convert_pts_to_figure.m` is uploaded now. Let me know if this is ok with you.

Yeah, this s what I need! Thank you very much for your generous sharing, it will help me a lot!
