### ISSUE TITLE
RuntimeError: uniform_ expects to return a [from, to) range, but found from=1 > to=0.02

### ISSUE THREAD

**Issue by Ella77** [Ha0Tang/C2GAN#3]
Thank you for your great repository! 

I encountered error in networks RuntimeError: uniform_ expects to return a [from, to) range, but found from=1 > to=0.02

some range transformation needed to solve this issue 

but I guess this could be something related to pytorch version error but same error appears on pytorch 0.4.1 :(

**Comment by Ha0Tang** [comment]
Would you provide more details?

**Comment by Ella77** [comment]
I guess it is just simple error regarding pytorch version (not working in 0.4.1+)

Replace   init.uniform(m.weight.data,  1.0, 0.02) with  init.uniform(m.weight.data,  0.02, 1.0) in models/networks.py
 resolves this issue.

**Comment by Ha0Tang** [comment]
Great.
