### ISSUE TITLE
abnormal output during training

### ISSUE THREAD

**Issue by sitadivon** [Ha0Tang/C2GAN#7]
Hi, I met a problem during training the network.

At train phase, due to opt.display_freq=1, at each step, 8 images are generated, where real_A, real_B, input_C, input_D should correspond to the input of the network. But I observed that they did not form a pair. See [the 12th epoch output](https://github.com/sitadivon/tmp/blob/master/epoch12_img.png).
In this picture, real_A and real_B are obviously not the same person.

I have read the code carefully, but I can’t find the reason. Do you know why this happened?

**Comment by Ha0Tang** [comment]
How about the outputs of the 11th epoch?

**Comment by sitadivon** [comment]
Only current training epoch is abnormal. All the previous outputs are normal.

**Comment by Ha0Tang** [comment]
I think it should be ok since the visualization is a bit delayed.

**Comment by sitadivon** [comment]
Sure. I can get right result at the end of every epoch. Thank you!
