### ISSUE TITLE
Why not add L1 loss of Keypoint generator?

### ISSUE THREAD

**Issue by sitadivon** [Ha0Tang/C2GAN#8]
The whole loss consists of:
GAN loss(both Keypoint and Image)
Cycle loss(both Keypoint and Image)
**L1 loss(Only Image)**

I wonder why you not add L1 loss of Keypoint. Did you experiment with that?

**Comment by Ha0Tang** [comment]
How to use the L1 loss of keypoint?

**Comment by sitadivon** [comment]
Sorry, I asked a stupid question. I didn't distinguish between cycle loss and L1 loss. Thank you for your patience!

**Comment by Ha0Tang** [comment]
No worries.
